name: dotnet package

on:
  push:
    branches:
      - main

jobs:
  build_netcore_app_3_1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      - name: Build
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/netcore-webapp3.1
      - uses: actions/upload-artifact@v2
        with:
          name: netcore-webapp3.1
          path: ./src/netcore-webapp3.1/publish

  build_netcore_app_5_0:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Build
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/netcore-webapp5.0
      - uses: actions/upload-artifact@v2
        with:
          name: netcore-webapp5.0
          path: ./src/netcore-webapp5.0/publish

  create_release:
    needs: [build_netcore_app_3_1, build_netcore_app_5_0]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: mkdir zip
      - uses: actions/download-artifact@v2
        with:
          name: netcore-webapp3.1
          path: zip
      - run: ls ./zip
      - uses: actions/download-artifact@v2
        with:
          name: netcore-webapp5.0
          path: zip
      - run: ls ./zip