name: dotnet package

on:
  push:
    branches:
      - main

jobs:
  build_netcore_app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      - name: Build
        run: dotnet publish --configuration Release
        working-directory: ./src/netcore-webapp3.1
      - name: Setup .NET Core SDK 5.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Build
        run: dotnet publish --configuration Release
        working-directory: ./src/netcore-webapp5.0

