name: dotnet package

on:
  push:
    branches:
      - main

jobs:
  build_netcore_app_3_1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      - name: Build
        run: dotnet publish -c Release -o ./bin/publish
        working-directory: ./src/netcore-webapp3.1
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r netcore-webapp3.1.zip  ./src/netcore-webapp3.1/bin/publish
      - uses: actions/upload-artifact@v2
        with:
          name: netcore-webapp3.1
          path: ./netcore-webapp3.1.zip

  build_netcore_app_5_0:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Build
        run: dotnet publish -c Release -o ./bin/publish
        working-directory: ./src/netcore-webapp5.0
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r netcore-webapp5.0.zip  ./src/netcore-webapp5.0/bin/publish
      - uses: actions/upload-artifact@v2
        with:
          name: netcore-webapp5.0
          path: ./netcore-webapp5.0.zip

  create_release:
    needs: [build_netcore_app_3_1, build_netcore_app_5_0]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: mkdir zip
      - uses: actions/download-artifact@v2
        with:
          name: netcore-webapp3.1
          path: zip
      - run: ls ./zip
      - uses: actions/download-artifact@v2
        with:
          name: netcore-webapp5.0
          path: zip
      - run: ls ./zip